---
version: 2

registries:
  dockerhub-registry:
    type: docker-registry
    url: registry.hub.docker.com
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_PASSWORD }}

updates:
  - package-ecosystem: docker
    directories:
      - "/src/images/debian-base"
      - "/src/images/debian-cdk"
      - "/src/images/debian-cdktf"
      - "/src/images/ubuntu-base"
    schedule:
      interval: daily
    commit-message:
      prefix: "build"
    registries: ["dockerhub-registry"]

  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "dev"
