---
name: 'PR dependabot dev-base'

on:
  pull_request:
    branches:
      - main
    paths:
      - './src/images/dev-base/Dockerfile'
      - './src/images/dev-base/docker-bake.hcl'

permissions:
  pull-requests: write
  contents: write

env:
  DOCKER_IMAGE: dev-base
  GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  test-build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: 'set shell options globally'
        run: set -euxo pipefail # fail on error, fail on unset variable, fail on pipe error
        shell: bash

      - name: 'set up qemu'
        uses: docker/setup-qemu-action@v3

      - name: 'set up docker buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'test build'
        uses: docker/bake-action@v5
        with:
          targets: test
          workdir: "./src/images/${{env.DOCKER_IMAGE}}"

      - name: 'dependabot metadata'
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{env.GH_TOKEN}}

      - name: 'auto-merge for dependabot prs'
        run: gh pr merge --auto --rebase ${{github.event.pull_request.number}}
        env:
          GITHUB_TOKEN: ${{env.GH_TOKEN}}
